# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gPlC-0H4tYZuXXVmwzbooNLCwX_LNEKv
"""

print("Welcome to credit card or debit card verifier (offline)")
card=str(input("Enter your 16 digit number without spaces: "))
if len(card)>16 or len(card)<16:
  print("Length provied error")
else:
  cardno = []
  for i in card:
    cardno.append(int(i))
  for i in range(len(cardno)):
    if (i % 2) != 0:
      cardno[i-1]=cardno[i-1]*2
  for i in range(len(cardno)):
    if cardno[i]>9:
      bo=str(cardno[i])
      res=[]
      for j in bo:
        res.append(int(j))
      cardno[i]=sum(res)
  if sum(cardno)%10==0:
    print("The card checks out")
  else:
    print("card not found")